import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useEffect, useState, type FormEvent } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { lovable } from '@/integrations/lovable';
import { Button } from '@/components/ui/button';
import groceries from '@/assets/kiwi-groceries.jpg';
import { Leaf } from 'lucide-react';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [{title:'Kiwi — Simple grocery planning'}, {name:'description',content:'Plan affordable groceries around your nutrition needs, without tracking every meal.'}, {property:'og:title',content:'Kiwi — Simple grocery planning'}, {property:'og:description',content:'A simpler way to shop for balanced meals.'}, {property:'og:type',content:'website'}, {name:'twitter:card',content:'summary_large_image'}] }),
  component: Welcome,
});
function Welcome(){
  const navigate=useNavigate(); const [mode,setMode]=useState<'login'|'signup'>('signup'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user) navigate({to:'/plan',replace:true});});},[navigate]);
  async function submit(e:FormEvent){e.preventDefault();setError('');setNotice('');setBusy(true); try{if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin, data:{display_name:name.trim()}}});if(error)throw error;if(data.session)navigate({to:'/plan'});else setNotice('Check your email to confirm your account, then sign in.');}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;navigate({to:'/plan'});}}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.');}finally{setBusy(false);}}
  async function google(){setError('');const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:window.location.origin});if(result.error)setError(result.error.message);else if(!result.redirected)navigate({to:'/plan'});}
  return <div className="auth-page"><div className="auth-content"><div className="brand brand-large"><span className="brand-icon"><Leaf size={23} strokeWidth={2.5}/></span><span>kiwi<span className="brand-dot">.</span></span></div><div className="auth-form-wrap"><div className="eyebrow">GOOD FOOD, LESS GUESSWORK</div><h1>Eating well starts<br/>with a better list<span className="brand-dot">.</span></h1><p className="auth-subtitle">Groceries that fit your life, your budget, and what your body needs. No food diary required.</p><div className="auth-tabs"><Button type="button" variant={mode==='signup'?'default':'ghost'} onClick={()=>{setMode('signup');setError('');setNotice('')}}>Create account</Button><Button type="button" variant={mode==='login'?'default':'ghost'} onClick={()=>{setMode('login');setError('');setNotice('')}}>Log in</Button></div><form onSubmit={submit} className="auth-form">{mode==='signup'&&<label>Your name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></label>}<label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="form-success" role="status">{notice}</p>}<Button className="auth-submit" disabled={busy} type="submit">{busy?'One moment…':mode==='signup'?'Create my account':'Log in'} <span aria-hidden>→</span></Button></form><div className="divider"><span>or</span></div><Button className="google-button" variant="outline" type="button" onClick={google}><span className="google-g">G</span> Continue with Google</Button><p className="auth-footnote">A calmer way to eat balanced, one grocery trip at a time.</p></div></div><div className="auth-photo"><img src={groceries} width={1024} height={1280} alt="A balanced grocery haul with chicken, fruit, vegetables and pantry staples"/><div className="photo-caption"><span className="photo-sparkle">✳</span><span>Real food.<br/>Real life.</span></div></div></div>;
}
