CREATE TABLE public.food_category (
  food_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_description varchar NOT NULL,
  category_serving_modifier double precision NOT NULL DEFAULT 1
);
CREATE TABLE public.food (
  food_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_picture varchar,
  food_name varchar NOT NULL,
  food_description text NOT NULL DEFAULT '',
  serving_size double precision NOT NULL DEFAULT 1,
  food_category_id integer REFERENCES public.food_category(food_category_id),
  unit varchar NOT NULL DEFAULT 'pack',
  price numeric NOT NULL DEFAULT 0,
  emoji varchar NOT NULL DEFAULT '',
  nutrition jsonb NOT NULL DEFAULT '{}'::jsonb,
  pairs integer[] NOT NULL DEFAULT '{}'
);
CREATE TABLE public.users (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name varchar NOT NULL DEFAULT '',
  last_name varchar NOT NULL DEFAULT '',
  user_picture varchar,
  email varchar NOT NULL DEFAULT ''
);
CREATE TABLE public.pantry (
  pantry_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES public.users(user_id) ON DELETE CASCADE
);
CREATE TABLE public.pantry_item (
  pantry_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pantry_id integer NOT NULL REFERENCES public.pantry(pantry_id) ON DELETE CASCADE,
  food_id integer NOT NULL REFERENCES public.food(food_id),
  quantity double precision NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit varchar,
  expiration_date date
);
CREATE TABLE public.shopping_list (
  shopping_list_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  days integer NOT NULL DEFAULT 7,
  budget numeric NOT NULL DEFAULT 75,
  status varchar NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);
CREATE TABLE public.shopping_list_item (
  shopping_list_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shopping_list_id integer NOT NULL REFERENCES public.shopping_list(shopping_list_id) ON DELETE CASCADE,
  food_id integer NOT NULL REFERENCES public.food(food_id),
  quantity double precision NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit varchar,
  is_purchased boolean NOT NULL DEFAULT false
);

GRANT SELECT ON public.food_category, public.food TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users, public.pantry, public.pantry_item, public.shopping_list, public.shopping_list_item TO authenticated;
GRANT ALL ON public.food_category, public.food, public.users, public.pantry, public.pantry_item, public.shopping_list, public.shopping_list_item TO service_role;

ALTER TABLE public.food_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pantry ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pantry_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shopping_list ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shopping_list_item ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read categories" ON public.food_category FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Anyone can read foods" ON public.food FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Users manage own user row" ON public.users FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users manage own pantry" ON public.pantry FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users manage own pantry items" ON public.pantry_item FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.pantry p WHERE p.pantry_id = pantry_item.pantry_id AND p.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.pantry p WHERE p.pantry_id = pantry_item.pantry_id AND p.user_id = auth.uid()));
CREATE POLICY "Users manage own shopping lists" ON public.shopping_list FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "Users manage own shopping list items" ON public.shopping_list_item FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.shopping_list s WHERE s.shopping_list_id = shopping_list_item.shopping_list_id AND s.user_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.shopping_list s WHERE s.shopping_list_id = shopping_list_item.shopping_list_id AND s.user_id = auth.uid()));

CREATE OR REPLACE FUNCTION public.handle_new_kiwi_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (user_id, email, first_name, last_name, user_picture)
  VALUES (NEW.id, COALESCE(NEW.email,''),
    COALESCE(NEW.raw_user_meta_data->>'first_name', split_part(COALESCE(NEW.raw_user_meta_data->>'full_name',''),' ',1), ''),
    COALESCE(NEW.raw_user_meta_data->>'last_name', ''),
    NEW.raw_user_meta_data->>'avatar_url')
  ON CONFLICT (user_id) DO NOTHING;
  INSERT INTO public.pantry (user_id) VALUES (NEW.id) ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END $$;
REVOKE EXECUTE ON FUNCTION public.handle_new_kiwi_user() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER on_auth_user_created_kiwi AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_kiwi_user();

INSERT INTO public.users (user_id, email) SELECT id, COALESCE(email,'') FROM auth.users ON CONFLICT DO NOTHING;
INSERT INTO public.pantry (user_id) SELECT user_id FROM public.users ON CONFLICT DO NOTHING;

COMMENT ON TABLE public.pantry_items IS 'DEPRECATED: replaced by pantry + pantry_item';
COMMENT ON TABLE public.trips IS 'DEPRECATED: replaced by shopping_list';
COMMENT ON TABLE public.trip_items IS 'DEPRECATED: replaced by shopping_list_item';